name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点自动运行（北京时间 08:00）
  workflow_dispatch:

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:  更新 WakaTime 数据
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: "AbsoluteZero001/AbsoluteZero001"   # 指向主页仓库
          SHOW_TITLE: "True"
          SHOW_TIME: "True"
          SHOW_TOTAL: "True"
          TIME_RANGE: "all_time"           # 全部时间
          LANG_COUNT: 10                   # 前10种语言
          SECTION_NAME: "waka_alltime"     # 对应 <!--START_SECTION:waka_alltime-->
          COMMIT_MESSAGE: "Update WakaTime Stats "
